[package]
name = "dnos"
version = "0.1.0"
edition = "2018"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
linker = "rust-lld"